# docker-compose.yml
version: "2"
services:
  covnertpdf:
    container_name: generarpdf_generico
#    image: api_cayman:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u app.py
    volumes:
      - /usr/local/volumes/fileserver/generarpdf_generico/:/app/fileserver/
    ports:
      - "5238:5238"